name: Branch Cleanup
on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Delete merged branches
        run: |
          echo "Fetching all branches..."
          git fetch --all --prune
          
          echo "Finding merged branches..."
          merged_branches=$(git branch -r --merged origin/main | grep -v "main\|develop\|HEAD" | sed 's/origin\///' || true)
          
          if [ -z "$merged_branches" ]; then
            echo "No merged branches to delete"
            exit 0
          fi
          
          echo "Branches to delete:"
          echo "$merged_branches"
          
          for branch in $merged_branches; do
            echo "Deleting branch: $branch"
            git push origin --delete "$branch" || echo "Failed to delete $branch (may not exist)"
          done
          
          echo "Branch cleanup completed"